pipeline { //Outer 
    agent any

    environment {
        DOCKER_HOST = 'tcp://127.0.0.1:2375'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Compile & Test Backend') {
            steps {
                dir('stationery-management') {
                    script {
                        if (isUnix()) {
                            sh 'mvn clean package'
                        } else {
                            bat 'mvn clean package'
                        }
                    }
                }
            }
        }

        stage('Build Frontend') {
            steps {
                dir('stationery-management/frontend') {
                    script {
                        if (isUnix()) {
                            sh 'npm install'
                            sh 'npm run build'
                        } else {
                            bat 'npm install'
                            bat 'npm run build'
                        }
                    }
                }
            }
        }

        stage('SonarQube Analysis') {
            steps {
                dir('stationery-management') {
                    catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                        script {
                            if (isUnix()) {
                                sh 'mvn sonar:sonar -Dsonar.projectKey=stationery-management -Dsonar.host.url=http://localhost:9000'
                            } else {
                                bat 'mvn sonar:sonar -Dsonar.projectKey=stationery-management -Dsonar.host.url=http://localhost:9000'
                            }
                        }
                    }
                }
            }
        }

        stage('Docker Build') {
            steps {
                dir('stationery-management') {
                    script {
                        if (isUnix()) {
                            sh 'docker-compose build'
                        } else {
                            bat 'docker-compose build'
                        }
                    }
                }
            }
        }

        stage('Deploy') {
            steps {
                dir('stationery-management') {
                    script {
                        if (isUnix()) {
                            sh 'docker-compose down'
                            sh 'docker-compose up -d'
                        } else {
                            bat 'docker-compose down'
                            bat 'docker-compose up -d'
                        }
                    }
                }
            }
        }
    }

    post {
        always {
            cleanWs()
        }
    }
}